resources:
  - ../../base

namespace: backend-qa

patchesStrategicMerge:
  - patches/replica-counts.yaml

configMapGenerator:
  - name: wep-admin-service-configmap
    literals:
      - aws_cognito_pool_id=your_cognito_pool_id
      - aws_region=us-east-1
      - app_env=backend-qa
      - node_env=development
      - wep_frontend_url=https://localhost:4200

# Remove this  
secretGenerator:
  - name: wep-admin-service-secret
    literals:
      - database_url=postgresql://test:test@test.com
      - aws_secrete_access_key=fake_secret
      - aws_access_key_id=fake_id
    