apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: dev-wildcard-cert-http01
  namespace: istio-ingress
spec:
  secretName: dev-wildcard-cert-http01
  revisionHistoryLimit: 1
  privateKey:
    rotationPolicy: Always
  # Note: HTTP-01 doesn't support wildcard certificates
  # You'll need individual certificates for each subdomain
  commonName: "dev.mocafi.com"
  dnsNames:
    - "dev.mocafi.com"
    - "api.dev.mocafi.com"
    - "app.dev.mocafi.com"
  usages:
    - digital signature
    - key encipherment
    - server auth
  issuerRef:
    name: letsencrypt-http01
    kind: ClusterIssuer
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-http01
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: your-email@example.com  # Update this
    privateKeySecretRef:
      name: letsencrypt-http01-private-key
    solvers:
    - http01:
        ingress:
          ingressTemplate:
            metadata:
              annotations:
                kubernetes.io/ingress.class: istio

