# HTTP-01 ClusterIssuer - Works without DNS coordination
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-http01
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: api-development@mocafi.com
    privateKeySecretRef:
      name: letsencrypt-http01-private-key
    solvers:
    - http01:
        ingress:
          ingressTemplate:
            metadata:
              annotations:
                kubernetes.io/ingress.class: istio

