apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-ecr-image-pull
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::<AWS number>:role/external-ecr-image-pull-role 
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: secrets-provider-aws
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::<AWS number>:role/external-ecr-image-pull-role